"""edit tables

Revision ID: aced3c062226
Revises: 951be13d5eb8
Create Date: 2024-06-17 08:51:32.862888

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aced3c062226"
down_revision: Union[str, None] = "951be13d5eb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_history", sa.Column("chat", sa.JSON(), nullable=False))
    op.drop_column("chat_history", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_history",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("chat_history", "chat")
    # ### end Alembic commands ###
