"""adit channel

Revision ID: de485e676b48
Revises: 6a3448a83716
Create Date: 2024-06-07 13:15:33.873148

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "de485e676b48"
down_revision: Union[str, None] = "6a3448a83716"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("channel", sa.Column("link", sa.String(), nullable=False))
    op.drop_column("channel", "update_at")
    op.drop_column("channel", "name")
    op.add_column(
        "group_of_channel", sa.Column("name", sa.String(), nullable=False)
    )
    op.add_column(
        "group_of_channel",
        sa.Column(
            "update_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_column("group_of_channel", "link")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "group_of_channel",
        sa.Column("link", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("group_of_channel", "update_at")
    op.drop_column("group_of_channel", "name")
    op.add_column(
        "channel",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "channel",
        sa.Column(
            "update_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("channel", "link")
    # ### end Alembic commands ###
